package main.enums;

public enum OccultistCombatSkills {
    SACRIFICIAL_STAB,
    ABYSSAL_ARTILLERY,
    WEAKENING_CURSE,
    WYRD_RECONSTRUCTION,
    VULNERABILITY_HEX,
    HANDS_FROM_ABYSS,
    DAEMON_PULL
} 